#!/bin/bash
water="water"
stir="stir"
bestchol="bestchol"

to_decimal() {
  local num=$1 base=$2
  local base_len=${#base}
  local dec=0
  local digit
  local i
  local char

  for (( i=0; i<${#num}; i++ )); do
    char="${num:$i:1}"
    digit=$(expr index "$base" "$char")
    ((digit--))
    (( dec = dec * base_len + digit ))
  done
  echo $dec
}

from_decimal() {
  local dec=$1 base=$2
  local base_len=${#base}
  local res=""
  local rem

  if (( dec == 0 )); then
    echo "${base:0:1}"
    return
  fi

  while (( dec > 0 )); do
    rem=$(( dec % base_len ))
    dec=$(( dec / base_len ))
    res="${base:rem:1}$res"
  done
  echo "$res"
}

dec_water=$(to_decimal "$WATER" "$water")
dec_stir=$(to_decimal "$STIR" "$stir")

sum=$(( dec_water + dec_stir ))

from_decimal $sum "$bestchol"
