#!/bin/bash
bash -c '
w="water"
s="stir"
o="bestchol"
to_dec() {
  local n=$1 b=$2 res=0 i c d base=${#b}
  for ((i=0;i<${#n};i++)); do
    c=${n:i:1}
    d=$(expr index "$b" "$c")
    ((d--))
    ((res=res*base+d))
  done
  echo $res
}
from_dec() {
  local n=$1 b=$2 r res base=${#b}
  if ((n==0)); then
    echo ${b:0:1}
    return
  fi
  while ((n>0)); do
    r=$((n%base))
    n=$((n/base))
    res=${b:r:1}$res
  done
  echo $res
}
res=$(( $(to_dec "$WATER" "$w") + $(to_dec "$STIR" "$s") ))
from_dec $res $o
'
