#!/usr/bin/env bash
# This script copies a file to a remote server automatically

# Check if you gave 4 inputs
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign the inputs to variables
FILE_TO_COPY=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Copy the file to the server's home folder without asking questions
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_TO_COPY" "$USERNAME@$SERVER_IP:~/"
