#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me with a 301 response

# Install Nginx if not already installed
sudo apt-get update -y
sudo apt-get install nginx -y

# Create the redirect configuration inside the default server block
sudo sed -i "/^\s*server {/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo systemctl reload nginx
