#!/usr/bin/env bash
# Sets up Nginx with a custom 404 page: "Ceci n'est pas une page"

# Install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Update Nginx default config to use the custom 404 page
sudo sed -i '/error_page 404/c\error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Reload Nginx
sudo systemctl reload nginx
