#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header with the hostname
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

systemctl enable nginx
systemctl start nginx

cat > /etc/nginx/conf.d/custom_headers.conf <<CONF
add_header X-Served-By \$hostname;
CONF

nginx -t
systemctl reload nginx
