#!/usr/bin/env bash
# Installs and configures HAProxy to load balance web-01 and web-02 using roundrobin

# shellcheck disable=SC2154

apt-get update -y
apt-get install -y haproxy

# Enable HAProxy to start on boot
systemctl enable haproxy

# Configure HAProxy backend
cat > /etc/haproxy/haproxy.cfg <<CONF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon
    maxconn 256

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 1287648-web-01:80 check
    server web-02 1287648-web-02:80 check
CONF

# Restart HAProxy to apply configuration
systemctl restart haproxy
